export interface IContextProps {
  instInfo: IInstituteProfile;
  userMeta: IUser;
  currentOrg: IOrgData;
  setCurrentOrg: (option: IOrgData) => void;
  planPermissions: IObject;
  webViewsEndPoint: string;
  institutionAddons?: IObject;
  apiEndPoint: string;
}

export interface IObject {
  key: string | number;
  value: string;
}

export interface ILogoDetail {
  logo_id: number;
  logo_institute_id: number;
  logo_field_id?: number;
  logo_url: string;
  logo_type: number;
  logo_height: string;
  logo_width: string;
  background_color: string;
  style: string;
}

export interface IInstituteProfile {
  institution_id: number;
  name: string;
  api_end_host: string;
  title: string;
  portal_name: string;
  logo_details: ILogoDetail[];
  contact_number: string;
  address_1: string;
  address_2: string;
  city: string;
  state: string;
  country: string;
  pincode: string;
  support_email: string;
  portal_link: string;
  show_courses: number;
  streams_visible: number;
  aboutus_visible: number;
  ios_link: string;
  android_link: string;
  enable_credit_system: number;
  is_live_classes_enabled: number;
  is_shopclients_enabled: number;
  shopclients_authtoken: string;
  enable_signup: number;
  payment_gateway: number;
  max_login_allowed: number;
  biometric_enabled: number;
  brand_colour: string;
  enable_gst: number;
  map_owners: number;
  enable_id_card: number;
  enable_my_payments: number;
  enable_buy_now: number;
  ispring_cloud_enabled: number;
  facebook_app_id: any;
  enable_otp_signup: number;
  show_student_rank: number;
  enable_video_download_android: number;
  enable_teacher_calling: number;
  enable_issue_certificate: number;
  course_info_buy_blocked: number;
  enable_fb_login: number;
  enable_google_login: number;
  terms_condition_url: string;
  privacy_policy_url: string;
  about_us_url: any;
  enable_student_profile_pic_update: number;
  institution_subdomain: string;
  host_name: string;
  fb_url: string;
  linked_url: string;
  twitter_url: string;
  ig_url: string;
  youtube_url: string;
  gplus_url: string;
  favicon_file_url: string;
  website_scripts: string;
  website_custom_style: string;
  free_enrol_btn_text: string;
  is_website_builder_set: number;
  remove_bottom_edmingle_logo: number;
  is_ssl_enabled: number;
  restrict_future_signin: number;
  allow_admin_virtualclass_signin: number;
  enable_certificate_tab: number;
  enable_certificate_verification: number;
  privacy_policy: any;
  terms_conditions: any;
  terms_conditions_url: any;
  signup_primary_field: number;
  institution_currency: number;
  actual_domain: string;
  client_enabled_gst: string;
  logout_url: string;
  student_logo_url: string;
  tutor_block_confidential_field: number;
  is_tutor_tnc_enabled: number;
  tutor_terms_and_conditions: string;
  enable_course_welcome_invoice_attachment: number;
  enable_invoice_attachment: any;
  is_sso_enabled: number;
  sso_client_url: string;
  enable_student_mark_material_as_completed: number;
  inst_base_currency_id: number;
  inst_international_selling_status: number;
  allow_course_access_branches: number;
  enable_website_builder: number;
  enforce_first_password_reset: number;
  allow_student_primary_field_edit: any;
  is_full_whitelabeled: string;
  edmingle_v2_node_url: string;
}
export interface IInstProfile {
  loading: boolean;
  institute: IInstituteProfile2 | null;
}
export interface IInstituteProfile2 {
  institution_id: number;
  name: string;
  top_banner: string;
  website: string;
  contact_number: string;
  api_end_host: string;
  title: string;
  portal_name: string;
  show_courses: number;
  streams_visible: number;
  aboutus_visible: number;
  portal_link: string;
  app_slides: any[];
  ios_link: string;
  android_link: string;
  enable_credit_system: number;
  is_live_classes_enabled: number;
  is_shopclients_enabled: number;
  shopclients_authtoken: string;
  enable_signup: number;
  payment_gateway: string;
  max_login_allowed: number;
  biometric_enabled: number;
  enable_gst: number;
  map_owners: number;
  enable_id_card: number;
  enable_my_payments: number;
  enable_buy_now: number;
  ispring_cloud_enabled: number;
  logo_details: ILogoDetail;
  facebook_app_id: any;
  enable_otp_signup: number;
  show_student_rank: number;
  enable_video_download_android: number;
  enable_teacher_calling: number;
  enable_issue_certificate: number;
  course_info_buy_blocked: number;
  enable_fb_login: number;
  enable_google_login: number;
  terms_condition_url: string;
  privacy_policy_url: string;
  about_us_url: any;
  enable_student_profile_pic_update: number;
  institution_subdomain: string;
  host_name: string;
  fb_url: string;
  linked_url: string;
  twitter_url: string;
  ig_url: string;
  youtube_url: string;
  gplus_url: string;
  is_website_builder_set: number;
  remove_bottom_edmingle_logo: number;
  is_ssl_enabled: number;
  restrict_future_signin: number;
  allow_admin_virtualclass_signin: number;
  enable_certificate_tab: number;
  is_programming_assignment_enabled: number;
  enable_certificate_verification: number;
  signup_primary_field: number;
  institution_currency: number;
  is_edmingle_payment_gateway: number;
  use_zoom_web_sdk: number;
  logout_url: string;
  student_logo_url: string;
  show_feedback_menu: number;
  show_messenger_section: number;
  enable_student_edit: number;
  show_introsliders: number;
  is_tutor_tnc_enabled: number;
  tutor_terms_and_conditions: string;
  referral_signup: number;
  referral_joins: number;
  enable_student_mark_material_as_completed: number;
  email_enabled: number;
  brand_colour: string;
  enable_class_ratings: number;
  referral_books_package: number;
  show_studentcount_courses: number;
  show_student_my_purchases: number;
  inst_base_currency_id: number;
  inst_international_selling_status: number;
  show_daily_updates_in_mobile: number;
  show_explore_courses_before_signup: number;
  facebook_pixel_key: any;
  is_facebook_pixel_enabled: number;
  contact_number_country_id: number;
  google_analytics_sdk_key: any;
  is_google_analytics_sdk_enabled: number;
  explore_courses_web_link: string;
  enable_signup_mobile: number;
  currency_promo_code_allowed: number[];
  allow_course_access_branches: number;
  enable_student_brand_colour: number;
  is_message_allowed: any;
  is_feedback_allowed: any;
  is_drm_enabled: number;
  drm_bunny_libraryid: number;
  is_sso_enabled: number;
  sso_client_url: string;
  is_grading_system_enabled: number;
  enable_youtube_masking: number;
  class_recording_for_instructors: number;
  is_mettl_enabled: number;
  video_completion_percentage: number;
  is_enterprise_drm_enabled: number;
  vdocipher_folder_id: string;
  support_email: string;
  allow_student_primary_field_edit: any;
  contact_number_dial_code: string;
  institute_logo_details: IInstituteLogoDetail[];
  custom_user_fields: any[];
  custom_text: ICustomText;
}

export interface ICustomText {
  free_enrol_btn_text: string;
}

export interface IInstituteLogoDetail {
  logo_id: number;
  logo_institute_id: number;
  logo_field_id?: number;
  logo_url: string;
  logo_type: number;
  logo_height: string;
  logo_width: string;
  background_color: string;
  style: string;
}
export interface IUser {
  user?: IUserObj;
}
export interface IUserObj {
  user_id: number;
  name: string;
  username: string;
  email: string;
  isAssignmentsEnabled: number;
  isQuizesEnabled: number;
  language: string;
  onboarding: number;
  signup_confirmed: number;
  country: string;
  course_onboarding: number;
  feedback_submitted: number;
  is_super_admin: number;
  is_parent: any;
  profile_picture_id: number;
  img_url: string;
  custom_form_filled: number;
  number_verified: number;
  first_name: string;
  last_name: string;
  level: number;
  exp: number;
  credits: number;
  contact_number: string;
  contact_number_2: string;
  address: string;
  emergency_contact: string;
  emergency_person: string;
  gender: string;
  occupation: number;
  birthday: number;
  freshchart_resume_id: string;
  is_tutor_tnc_enabled: any;
  google_id: string;
  new_release_notes: number;
  contact_number_country_id: number;
  contact_number_2_country_id: number;
  automatic_timezone_selection: number;
  password_updated_at: number;
  contact_number_dial_code: string;
  contact_number_2_dial_code: string;
  timezone: string;
  institution_id: number;
  is_institution_admin: number;
  alternate_login: number;
  org_data: IOrgData[];
  institution_currency: number;
  plan_settings: IPlanSetting[];
  plandetails: IPlandetails;
  temp_storage_warning: number;
  temp_subscription_warning: number;
  temp_storage_message: string;
  if_tutor_accepted_tnc: number;
}
export interface IOrgData {
  role: string;
  organization_id: number;
  organization_name: string;
  institution_id: number;
  institution_name: string;
  organization_state: string;
  organization_contact_number?: string;
  organization_contact_number_country_id?: number;
  organization_contact_number_dial_code: string;
  justdial_link: string;
  fb_link: string;
  youtube_link: string;
  google_business_link: string;
  status: string;
  is_freshchat_enabled: number;
  portal_name: string;
  organization_currency: number;
  currency_id: number;
  currency_symbol: string;
  label?: string;
  value?: string;
}

export interface IPlanSetting {
  id: number;
  setting_id: number;
  setting_key: string;
  setting_value: string;
  data_type: string;
  plan_level: number;
}
export interface IPlandetails {
  isplantrial: boolean;
  leftdays: number;
  is_reseller: any;
  is_planautodowngrade: any;
  is_planautodowngrade_date: any;
  is_zoomautodowngrade: any;
  is_zoomautodowngrade_date: any;
  is_custom: any;
}
